export const BUSINESS_INFO = {
  name: "Rajabakkiam Traders",
  phone: "+91 9003320069",
  phoneDisplay: "+91 90033 20069",
  email: "dafyadrien@gmail.com",
  address: "25/2, Andal Nagar, Chinnathirupathi, Salem - 8",
  city: "Salem",
  state: "Tamil Nadu",
  hours: "Mon–Sat, 8am–8pm",
  whatsappLink: "https://wa.me/919003320069",
  googleMapsEmbed: "https://maps.google.com/maps?q=11.6808076,78.1646515&z=15&output=embed",
};

export const RICE_PRODUCTS = [
  {
    id: "white-ponni",
    name: "White Ponni",
    tamilName: "வெள்ளை பொன்னி",
    description: "Premium quality white ponni rice, perfect for everyday cooking. Soft texture and great taste.",
    packSizes: ["1kg", "5kg", "10kg", "25kg"],
    category: "rice",
    image: "rice-ponni",
  },
  {
    id: "bpt-ponni",
    name: "BPT Ponni",
    tamilName: "ராஜபோகம்",
    description: "Fine-grain BPT Ponni rice known for its aroma and fluffy texture when cooked.",
    packSizes: ["1kg", "5kg", "10kg", "25kg"],
    category: "rice",
    image: "rice-ponni",
  },
  {
    id: "dlx-ponni",
    name: "DLX Ponni",
    tamilName: "DLX பொன்னி",
    description: "Deluxe quality ponni rice with superior grain quality and taste.",
    packSizes: ["5kg", "10kg", "25kg"],
    category: "rice",
    image: "rice-ponni",
  },
  {
    id: "nei-kichadi",
    name: "Nei Kichadi Ponni",
    tamilName: "நெய் கிச்சடி பொன்னி",
    description: "Special variety ideal for making kichadi and ghee rice preparations.",
    packSizes: ["5kg", "10kg", "25kg"],
    category: "rice",
    image: "rice-ponni",
  },
  {
    id: "idly-rice",
    name: "Idly Rice",
    tamilName: "இட்லி அரிசி",
    description: "Short-grain rice specifically processed for making soft, fluffy idlis.",
    packSizes: ["1kg", "5kg", "10kg"],
    category: "rice",
    image: "rice-idly",
  },
  {
    id: "kai-vekaattu",
    name: "Kai Vekaattu Arisi",
    tamilName: "கை வெகாட்டு அரிசி",
    description: "Traditional hand-pounded rice with authentic taste and health benefits.",
    packSizes: ["1kg", "5kg"],
    category: "rice",
    image: "rice-ponni",
  },
  {
    id: "brown-rice",
    name: "Brown Rice",
    tamilName: "பிரவுன் அரிசி",
    description: "Nutrient-rich brown rice with fiber and essential minerals intact.",
    packSizes: ["1kg", "5kg"],
    category: "rice",
    image: "rice-brown",
  },
  {
    id: "karuppu-kavuni",
    name: "Karuppu Kavuni",
    tamilName: "கருப்பு கவுனி",
    description: "Ancient black rice variety, rich in antioxidants and perfect for desserts.",
    packSizes: ["500g", "1kg"],
    category: "rice",
    image: "rice-black",
  },
  {
    id: "sivappu-arisi",
    name: "Sivappu Arisi",
    tamilName: "சிவப்பு அரிசி",
    description: "Traditional red rice with high nutritional value and earthy flavor.",
    packSizes: ["1kg", "5kg"],
    category: "rice",
    image: "rice-red",
  },
  {
    id: "moongil-arisi",
    name: "Moongil Arisi",
    tamilName: "மூங்கில் அரிசி",
    description: "Rare bamboo rice with unique flavor, harvested from bamboo flowers.",
    packSizes: ["500g", "1kg"],
    category: "rice",
    image: "rice-brown",
  },
  {
    id: "basmati",
    name: "India Gate Basmati",
    tamilName: "பாஸ்மதி அரிசி",
    description: "Premium long-grain basmati rice, perfect for biryani and pulao.",
    packSizes: ["1kg", "5kg"],
    category: "rice",
    image: "rice-basmati",
  },
];

export const GROCERY_PRODUCTS = [
  {
    id: "wheat-flour",
    name: "Wheat Flour",
    tamilName: "கோதுமை மாவு",
    description: "Fresh ground wheat flour for chapatis and rotis.",
    packSizes: ["1kg", "5kg", "10kg"],
    category: "grocery",
    image: "groceries",
  },
  {
    id: "edible-oil",
    name: "Edible Oil",
    tamilName: "சமையல் எண்ணெய்",
    description: "Quality cooking oils including groundnut, sunflower, and gingelly oil.",
    packSizes: ["1L", "5L", "15L"],
    category: "grocery",
    image: "groceries",
  },
  {
    id: "sugar",
    name: "Sugar",
    tamilName: "சர்க்கரை",
    description: "Pure white sugar for all your sweetening needs.",
    packSizes: ["1kg", "5kg"],
    category: "grocery",
    image: "groceries",
  },
  {
    id: "millets",
    name: "Millets",
    tamilName: "சிறுதானியங்கள்",
    description: "Variety of healthy millets including ragi, jowar, and bajra.",
    packSizes: ["500g", "1kg"],
    category: "grocery",
    image: "millets",
  },
];

export const PREMIUM_BRANDS = [
  {
    id: "cherry",
    name: "CHERRY",
    tamilName: "செர்ரி",
    description: "Premium rice brand from the fertile lands of Kangayam, known for quality and purity.",
    packSizes: ["10kg", "25kg", "75kg"],
    category: "premium-brand",
    image: "rice-ponni",
  },
  {
    id: "rettaikili",
    name: "RETTAIKILI",
    tamilName: "இரட்டைக்கிளி",
    description: "Local Salem brand trusted by generations for consistent quality rice.",
    packSizes: ["10kg", "25kg", "75kg"],
    category: "premium-brand",
    image: "rice-ponni",
  },
  {
    id: "malgova",
    name: "MALGOVA",
    tamilName: "மால்கோவா",
    description: "Traditional brand offering authentic Kangayam rice varieties.",
    packSizes: ["10kg", "25kg", "75kg"],
    category: "premium-brand",
    image: "rice-ponni",
  },
  {
    id: "india-gate",
    name: "India Gate",
    tamilName: "இந்தியா கேட்",
    description: "Premium basmati rice brand known for long grains and aromatic flavor.",
    packSizes: ["1kg", "5kg", "20kg"],
    category: "premium-brand",
    image: "rice-basmati",
  },
  {
    id: "double-deer",
    name: "Double Deer",
    tamilName: "டபுள் டீர்",
    description: "Specialty zeera rice perfect for special occasions and biryani.",
    packSizes: ["1kg", "5kg", "25kg"],
    category: "premium-brand",
    image: "rice-ponni",
  },
  {
    id: "royal-bullet",
    name: "Royal Bullet",
    tamilName: "ராயல் புல்லட்",
    description: "High-quality rice brand offering various premium rice varieties.",
    packSizes: ["10kg", "25kg"],
    category: "premium-brand",
    image: "rice-ponni",
  },
];

export const BENEFITS = [
  {
    icon: "Award",
    title: "Superb Fine Quality",
    description: "Only the finest grains from trusted sources",
  },
  {
    icon: "Truck",
    title: "Free Delivery up to 10km",
    description: "Complimentary delivery within Salem city",
  },
  {
    icon: "BadgeIndianRupee",
    title: "Reasonable Price",
    description: "Fair prices for premium quality products",
  },
  {
    icon: "Heart",
    title: "Friendly Service",
    description: "Personal attention to every customer",
  },
  {
    icon: "Zap",
    title: "Quick Response",
    description: "Fast order confirmation and delivery",
  },
];
